import tkinter as tk
import json
import subprocess
with open("Lube/config.json", "r") as file:
    configfile = json.load(file)
maincolor = configfile["main_color"]
selectedcolor = configfile["selected_color"]
def hide_frame1_widgets():
    frame1.place_forget()
    frame1browser.pack_forget()
    frame1lube.pack_forget()
    frame1made.pack_forget()
    frame1social.pack_forget()
def show_frame1_widgets():
    frame1.place(x=150, y=50, width=450, height=450)
    frame1browser.pack(pady=5)
    frame1lube.pack(pady=5)
    frame1made.pack(pady=5)
    frame1social.pack(pady=5)
def hide_frame2_widgets():
    frame2.place_forget()
    frame2mc.place_forget()
    frame2d.place_forget()
def show_frame2_widgets():
    frame2.place(x=150, y=50, width=450, height=450)
    frame2mc.place(x=0, y=0, height=50, width=450)
    frame2d.place(x=0, y=50, height=50, width=450)
def but1():
    print("Button1: Info")
    sideframebut1.config(background=selectedcolor)
    sideframebut2.config(background=maincolor)
    sideframebut3.config(background=maincolor)
    sideframebut4.config(background=maincolor)
    sideframebut5.config(background=maincolor)
    show_frame1_widgets()
    hide_frame2_widgets()
def but2():
    print("Button2: Appearance")
    sideframebut1.config(background=maincolor)
    sideframebut2.config(background=selectedcolor)
    sideframebut3.config(background=maincolor)
    sideframebut4.config(background=maincolor)
    sideframebut5.config(background=maincolor)
    hide_frame1_widgets()
    show_frame2_widgets()
def but3():
    print("Button3: LAccount")
    sideframebut1.config(background=maincolor)
    sideframebut2.config(background=maincolor)
    sideframebut3.config(background=selectedcolor)
    sideframebut4.config(background=maincolor)
    sideframebut5.config(background=maincolor)
    hide_frame1_widgets()
    hide_frame2_widgets()
def but4():
    print("Button4: Addons")
    sideframebut1.config(background=maincolor)
    sideframebut2.config(background=maincolor)
    sideframebut3.config(background=maincolor)
    sideframebut4.config(background=selectedcolor)
    sideframebut5.config(background=maincolor)
    hide_frame1_widgets()
    hide_frame2_widgets()
def but5():
    print("Button5: Dev. Mode")
    sideframebut1.config(background=maincolor)
    sideframebut2.config(background=maincolor)
    sideframebut3.config(background=maincolor)
    sideframebut4.config(background=maincolor)
    sideframebut5.config(background=selectedcolor)
    hide_frame1_widgets()
    hide_frame2_widgets()
def cmasc():
    subprocess.run(["python", "Lube/other/changeappearance.py"])
def cmascd():
    with open("Lube/config.json", "r") as file:
        config = json.load(file)
    config["main_color"] = "green"
    config["selected_color"] = "lightgreen"
    with open("Lube/config.json", "w") as file:
        json.dump(config, file, indent=4)
    print("Configuration updated!")
setroot = tk.Tk()
setroot.title("Settings")
setroot.geometry("600x500")
setroot.iconbitmap("Lube/source/icon.ico")
topframe = tk.Frame(setroot, background=maincolor)
topframe.place(x=0, y=0, width=600, height=50)
lubetext = tk.Label(topframe, text="Settings", font=('Fredoka', 18), background=maincolor)
lubetext.pack(padx=10, pady=5)
sideframe = tk.Frame(setroot, background=maincolor)
sideframe.place(x=0, y=0, height=500, width=150)
sideframebut1 = tk.Button(sideframe, text="Info", font=('Fredoka', 15), background=selectedcolor, command=but1)
sideframebut1.place(x=0, y=50, height=50, width=150)
sideframebut2 = tk.Button(sideframe, text="Appearance", font=('Fredoka', 15), background=maincolor, command=but2)
sideframebut2.place(x=0, y=100, height=50, width=150)
sideframebut3 = tk.Button(sideframe, text="LAccount", font=('Fredoka', 15), background=maincolor, command=but3)
sideframebut3.place(x=0, y=150, height=50, width=150)
sideframebut4 = tk.Button(sideframe, text="Addons (coming soon!)", font=('Fredoka', 10), background=maincolor, command=but4)
sideframebut4.place(x=0, y=200, height=50, width=150)
sideframebut5 = tk.Button(sideframe, text="Developer mode", font=('Fredoka', 14), background=maincolor, command=but5)
sideframebut5.place(x=0, y=250, height=50, width=150)
frame1 = tk.Frame(setroot, background=selectedcolor)
frame1browser = tk.Label(frame1, text="Lube Browser v0.2.2", font=('Fredoka', 14), background=selectedcolor)
frame1lube = tk.Label(frame1, text="Lube Web v0.2.0", font=('Fredoka', 14), background=selectedcolor)
frame1made = tk.Label(frame1, text="Made by Lucas", font=('Fredoka', 14), background=selectedcolor)
frame1social = tk.Label(frame1, text="YT: @lucasgamer0001", font=('Fredoka', 14), background=selectedcolor)
frame2 = tk.Frame(setroot, background=selectedcolor)
frame2mc = tk.Button(frame2, text="Change main and selected colors", font=('Fredoka', 14), background=selectedcolor, command=cmasc)
frame2d = tk.Button(frame2, text="Deafult colors", font=('Fredoka', 14), background=selectedcolor, command=cmascd)
frame3 = tk.Frame(setroot, background=selectedcolor)
frame4 = tk.Frame(setroot, background=selectedcolor)
frame5 = tk.Frame(setroot, background=selectedcolor)
frame5.place(x=150, y=50, width=450, height=450)
frame5text = tk.Label(frame5, text="Developer mode", font=('Fredoka', 15), background=selectedcolor)
frame5text.pack(pady=5)
frame5stat = tk.Label(frame5, text="OFF", font=('Fredoka'), background=selectedcolor)  
frame5stat.pack(pady=5)
frame5button = tk.Button(frame5, text="Turn off", font=('Fredoka'), background=selectedcolor)
frame5button.pack(pady=5)
hide_frame1_widgets()
hide_frame2_widgets()
setroot.mainloop()